name: Test Project
on: push 
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout File
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
           node-version: 18
      - name: 'Resolve Project Dependencies Using Npm'
        run: npm ci
      - name: npm test
        run: npm run test